spring.datasource.url=jdbc:postgresql://postgres:5432/gamesdonequack_db?charSet=UTF8
spring.datasource.username=dev_db_user
spring.datasource.password=temp

security.enable-basic=false
security.disable-csrf=false
security.enable-super-login=false

docker.mode-enabled=true

#spring security more explicit in debug logs : 
logging.level.org.springframework.security=DEBUG