spring.datasource.url=jdbc:postgresql://localhost:5432/gamesdonequack_db?charSet=UTF8
spring.datasource.username=dev_db_user
spring.datasource.password=temp

security.enable-basic=true
security.disable-csrf=true